MFC r236149:
Pull in r157212 from upstream clang trunk:

  Revert r115805. An array type is required to have a range type,
  however, the range can be unknown for the upper bound.

  Testcase to follow.

  Part of rdar://11457152

This should fix ctfconvert producing error messages during kernel
builds, similar to:

  ERROR: scsi_all.c: die 24561: failed to retrieve array bounds

These were caused by incorrect debug information for flexible array
members of structs.


git-svn-id: svn://svn.freebsd.org/base/stable/9@236296 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f